name: VanillaPlayerList
version: 1.0
author: simon@ceilingcat.ch
website: https://github.com/sadimusi/VanillaPlayerList

main: ch.ceilingcat.vanillatablist.VanillaPlayerList
depend: [TabAPI, ProtocolLib]
